# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GitCat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'AlamofireObjectMapper'
  pod 'ObjectMapper'
  pod 'Kingfisher'

  # Pods for GitCat


end
