# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GitCat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for GitCat
  
  pod 'Alamofire','= 5.0.0-rc.2'
  pod 'AlamofireObjectMapper'
  pod 'ObjectMapper'
  pod 'Kingfisher'
  pod 'FSCalendar'
end
