# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GitCat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for GitCat
  pod 'Alamofire', '4.7.3'
  pod 'Kingfisher'
  pod 'FSCalendar'
  pod 'SwiftyJSON'
  pod 'SwiftGifOrigin'
  pod 'CryptoSwift'
  pod 'JWTDecode'
end
